[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = { "" = "src" }

[project]
name = "ideal-gas"
version = "0.0.1"
description = "A Python module for calculating The Ideal Gas Law, focusing make it easy and high school-friendly"
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.10"
dependencies = []

authors = [
    { name = "Natthanan", email = "nattanan43658@gmail.com" }
]

classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Chemistry",
    "Intended Audience :: Education",
]

[project.urls]
Homepage = "https://github.com/Narngisa/Ideal-gas"
Repository = "https://github.com/Narngisa/Ideal-gas"
Issues = "https://github.com/Narngisa/Ideal-gas/issues"
